### ISSUE TITLE
[CLI] List devices command-line flag

### ISSUE THREAD

**Issue by cpebble** [chregon2001/lc#5]
Having a `list-devices` flag for scripting purposes etc would be nice. Current behavior only list under help text

**Comment by chregon2001** [comment]
Agree, but i think we should have some general mechanism for flags. I see many cases where these are coded to fit (i.e. no libraries for handling stdin), and i wonder if this is the right way to go about this? @cpebble

**Comment by cpebble** [comment]
I recommend GNU getopt
https://www.gnu.org/software/libc/manual/html_node/Getopt.html

**Comment by chregon2001** [comment]
18af0c1bc01df69eac7984cf15dc95f1ffd472da implemented this, and as a bonus, i made a dirty hack so that we can have "bare" negative numbers. Closing.
