### ISSUE TITLE
[CLI] Support relative lighting changes

### ISSUE THREAD

**Issue by cpebble** [chregon2001/lc#7]
Set relative lighting changes such as `lc intel_backlight +5` 

I need this to use lc in i3 so i can script backlight changes

**Comment by chregon2001** [comment]
I will look into this asap, should have a pr by tomorrow.

**Comment by chregon2001** [comment]
Looks like it would make sense to do #5 first, so small delay

**Comment by chregon2001** [comment]
18af0c1bc01df69eac7984cf15dc95f1ffd472da implemented this, but introduced some code debt... closing
